FROM php:8.1-fpm

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl channel-update pecl.php.net && \
    # версию пакета oci8 для установки можно проверять здесь https://pecl.php.net/package/xdebug
    pecl install xdebug-3.1.5

RUN mkdir -p /var/log/php

WORKDIR /var/www
EXPOSE 9000
CMD ["php-fpm"]
