version: '3'

networks:
  iptv:
    driver: bridge

services:

  php:
    container_name: iptv-php
    build: 'docker/php'
    restart: unless-stopped
    networks:
      - iptv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./log/php:/var/log/php:rw
      - ./app:/var/www:rw
      # - ./docker/php/xdebug:/var/xdebug:rw
    # ports:
    #   - "9090:9000"

  nginx:
    container_name: iptv-nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      - iptv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./log/nginx:/var/log/nginx:rw
      - ./app:/var/www:ro
    ports:
      - 8080:80
    links:
      - php
    depends_on:
      - php
